// <auto-generated />
using System;
using HEMedical.Hospital;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HEMedical.Hospital.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260529192427_AddEnumToStringConverter")]
    partial class AddEnumToStringConverter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("ClinicalMeasurementSequence");

            modelBuilder.Entity("HEMedical.Hospital.Models.ClinicalMeasurementModels.ClinicalMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [ClinicalMeasurementSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<string>("InterpretationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterpretationSystem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("HEMedical.Hospital.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("HEMedical.Hospital.Models.ClinicalMeasurementModels.BloodPressure", b =>
                {
                    b.HasBaseType("HEMedical.Hospital.Models.ClinicalMeasurementModels.ClinicalMeasurement");

                    b.Property<decimal>("Diastolic")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("Systolic")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.ToTable("BloodPressure");
                });

            modelBuilder.Entity("HEMedical.Hospital.Models.ClinicalMeasurementModels.Hb1Ac", b =>
                {
                    b.HasBaseType("HEMedical.Hospital.Models.ClinicalMeasurementModels.ClinicalMeasurement");

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.ToTable("Hb1Ac");
                });

            modelBuilder.Entity("HEMedical.Hospital.Models.ClinicalMeasurementModels.ClinicalMeasurement", b =>
                {
                    b.HasOne("HEMedical.Hospital.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
